version: '3'
services:
  illyria-forum: #name of your service
    build: ./ # specify the directory of the Dockerfile
    restart: always
    container_name: flarum-service
    ports:
      - "3025:80"
    links:
      - database # link this service to the database service
    depends_on:
      - database

  database: # name of the service
    image: mariadb # specify image to build container from
    container_name: flarum-database
    env_file: 
        - db.env